language: java
addons:
  sonarcloud:
    organization: "giantpanda0090-github"
    token:
      secure: SONAR_TOKEN
    github_token:
      secure: GITHUB_TOKEN
      branches:
      - master
script:
  - sonar-scanner
