language: java
addons:
  sonarcloud:
    organization: "giantpanda0090-github"
    token:
      secure: $SONAR_TOKEN
       branches:
       - master
    github_token:
      secure: $GITHUB_TOKEN
    
script:
  - sonar-scanner
