language: java

jdk:
  - oraclejdk8  
    
addons:
  sonarcloud:
    organization: "giantpanda0090-github"
    token: $SONAR_TOKEN
    github_token: $GITHUB_TOKEN
    
script:
  - build-wrapper --out-dir bw-outputs ./build.sh
  - sonar-scanner
