language: java

jdk:
  - oraclejdk8

branches:
  only:
  - master
  
    
addons:
addons:
  apt:
    packages:
      - oracle-java8-installer
      
  sonarcloud:
    organization: "giantpanda0090-github"
    token: $SONAR_TOKEN
    github_token: $GITHUB_TOKEN
    
script:
  - sonar-scanner
