language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "giantpanda0090-github"
    token: $SONAR_TOKEN
       branches:
       - master
    github_token: $GITHUB_TOKEN
    
script:
  - sonar-scanner
