language: java
jdk:
  - oraclejdk8
  
before_install:
    - rm -rf ~/.linuxbrew
    - yes | ruby -e "$(url -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    - export PATH="$HOME/.linuxbrew/bin:$PATH"
    - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
    - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
    - brew install jdk
    - export JAVA_HOME=/home/travis/.linuxbrew/Cellar/jdk/1.8.0-40
    
addons:
  sonarcloud:
    organization: "giantpanda0090-github"
    token: $SONAR_TOKEN
    github_token: $GITHUB_TOKEN
    
script:
  - sonar-scanner
